# GENERATED by apps/audit-console/sync_engine.py -- do not edit.
#
# A copy of pythonlib/camoufox/audit/__init__.py, vendored so the console ships
# as one self-contained file. Edit the source and re-run the sync.
#
# Copied verbatim except for the browser imports noted below: the engine reaches
# for `..async_api` and `..proxy` lazily, from inside the browser rungs, and after
# relocation `..` no longer means `camoufox`. They are rewritten to the absolute
# package so an installed camoufox is used when present. Everything the HTTP rung
# needs (L0) stays dependency-free.

"""
WAF / bot-defense audit tooling.

Answers one question honestly: given a target that the operator is authorized to
test, which of its defenses actually hold as the client looks less like a bot?

The design centers on *attribution*. A single pass/fail is not actionable -- it
tells the operator to turn everything up, which is how a site acquires a WAF that
blocks a real customer. Running an ordered ladder of client postures isolates the
control that is doing the work, so each finding points at one defense.

Traffic realism is a requirement, not a flourish. Arrivals are sampled from a
diurnal distribution rather than spaced evenly; each browser rung gets its own
window so no arrival time is shared between postures; and the behavioral rung
moves a pointer, holds its clicks, scrolls with momentum and types at a drawn
cadence. A run that is separable from real traffic measures the operator's
detection of *this tool* rather than the defense under test.

Safety is structural, not advisory:

* nothing runs without an acknowledged :class:`~camoufox.audit.scope.TargetScope`;
* every navigation passes a scope check, so an off-target link cannot be followed;
* a request ceiling, an RPS ceiling, a concurrency ceiling, an arrivals-per-minute
  ceiling and an abort-on-consecutive-errors rule cap the traffic;
* a level that hits a ceiling is reported as aborted, with the reason, rather than
  as a clean result.

What this deliberately does *not* do: solve CAPTCHAs, exploit vulnerabilities, or
replay credentials. Detecting that a challenge was issued is the finding; solving
it would defeat the defense under test and blind the operator to it.
"""

from .behavior import BehaviorModel, Cursor
from .config import (
    SINGLE_LEVEL_VISITORS,
    AuditConfig,
    AuditReport,
    CampaignEvent,
    LevelResult,
    SafetyLimits,
    VisitResult,
)
from .detection import Verdict, WafDetection, classify_response, detect_vendor
from .evasion import (
    CAPABILITIES,
    EVASION_LEVELS,
    UNCONTROLLABLE_HEADERS,
    EvasionLevel,
    ladder_problems,
    level_by_id,
    levels_up_to,
)
from .journey import (
    ArrivalSource,
    BannerCandidate,
    JourneyConfig,
    OutboundPlan,
    VisitPlan,
    discover_banner_candidates,
    is_ad_syndication_url,
    parse_rate_pct,
    plan_outbound_visit,
    plan_visit,
)
from .runner import AuditRunner, SafetyStop, run_audit
from .schedule import Arrival, ArrivalPattern, Schedule, ScheduleConfig, build_schedule
from .scope import (
    AuthorizationRequired,
    ScopeViolation,
    TargetScope,
    registrable_domain,
)

__all__ = [
    # config
    "AuditConfig",
    "SafetyLimits",
    "VisitResult",
    "CampaignEvent",
    "LevelResult",
    "AuditReport",
    "SINGLE_LEVEL_VISITORS",
    # behavior
    "BehaviorModel",
    "Cursor",
    # scope
    "TargetScope",
    "registrable_domain",
    "ScopeViolation",
    "AuthorizationRequired",
    # detection
    "Verdict",
    "WafDetection",
    "classify_response",
    "detect_vendor",
    # evasion ladder
    "EvasionLevel",
    "EVASION_LEVELS",
    "CAPABILITIES",
    "UNCONTROLLABLE_HEADERS",
    "ladder_problems",
    "level_by_id",
    "levels_up_to",
    # schedule
    "ScheduleConfig",
    "Schedule",
    "Arrival",
    "ArrivalPattern",
    "build_schedule",
    # journey
    "JourneyConfig",
    "VisitPlan",
    "ArrivalSource",
    "plan_visit",
    # outbound funnel
    "BannerCandidate",
    "OutboundPlan",
    "discover_banner_candidates",
    "is_ad_syndication_url",
    "parse_rate_pct",
    "plan_outbound_visit",
    # runner
    "AuditRunner",
    "run_audit",
    "SafetyStop",
]