# GENERATED by apps/audit-console/sync_engine.py -- do not edit.
#
# A copy of pythonlib/camoufox/audit/evasion.py, vendored so the console ships
# as one self-contained file. Edit the source and re-run the sync.
#
# Copied verbatim except for the browser imports noted below: the engine reaches
# for `..async_api` and `..proxy` lazily, from inside the browser rungs, and after
# relocation `..` no longer means `camoufox`. They are rewritten to the absolute
# package so an installed camoufox is used when present. Everything the HTTP rung
# needs (L0) stays dependency-free.

"""
The evasion ladder: which defenses hold as the client looks less like a bot.

A single "did we get in?" answer cannot be acted on. If the audit fails at the
top level, the operator learns nothing about *which* control stopped it, so they
cannot tune anything -- they can only turn defenses up, which is how sites end up
with a WAF nobody understands.

Running the same target at increasing levels isolates cause from effect. The
first level whose verdict flips from allowed to detected is the control that is
actually doing the work. Everything below it is already defeated and is dead
weight; everything above it is untested and unknown.

The ladder is ordered by cost, cheapest first, so a cheap defense that holds
means the audit stops early instead of building an elaborate browser for nothing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

__all__ = [
    "CAPABILITIES",
    "UNCONTROLLABLE_HEADERS",
    "EvasionLevel",
    "EVASION_LEVELS",
    "level_by_id",
    "levels_up_to",
    "ladder_problems",
]

#: The axes the ladder is allowed to vary, in the order they are introduced.
#:
#: The ladder's whole claim is that each rung differs from the one below by
#: exactly *one* of these. Without a name for each axis that claim is only a
#: comment: nothing stops a rung from quietly turning on two things at once (or
#: from repeating the rung below it verbatim), and either mistake makes the
#: ladder unable to attribute a verdict to a control. Naming the axes is what
#: lets `ladder_problems()` and the runner gate on them.
CAPABILITIES: Tuple[str, ...] = (
    # A real engine instead of a raw HTTP client.
    "browser",
    # A coherent navigation header set (UA, Accept, Sec-Fetch-*, Referer).
    "headers",
    # A spoofed, geo/timezone-aligned fingerprint from the anti-detect engine.
    "fingerprint",
    # A fresh exit IP per visitor, from a proxy pool.
    "ip_rotation",
    # Human cadence: a planned journey plus humanized input.
    "behavior",
    # A durable profile and cookie jar, rather than a throwaway context.
    "persistence",
)

#: Headers a rung may not rely on controlling.
#:
#: Measured on the wire: Firefox generates these itself and will not let a route
#: override or remove them -- `route.continue_(headers=...)` was asked for each of
#: them and each arrived unchanged. They are listed so a rung that declares one can
#: be caught: a header the client cannot actually change is a no-op that reads like
#: a control, and it would make the rung's `adds` claim false while the ladder's own
#: consistency check saw nothing wrong.
#:
#: `User-Agent`, `Accept`, `Accept-Language` and `Cache-Control` are deliberately
#: *not* here -- they are settable, and a rung that pins a wrong one is caught by
#: its own coherence tests (engine/UA agreement, locale agreement) rather than
#: being dismissed as impossible.
UNCONTROLLABLE_HEADERS: frozenset = frozenset(
    {
        "sec-fetch-dest",
        "sec-fetch-mode",
        "sec-fetch-site",
        "sec-fetch-user",
        "upgrade-insecure-requests",
        "accept-encoding",
        "connection",
        "host",
        "referer",
    }
)


@dataclass(frozen=True)
class EvasionLevel:
    """
    One rung: a client posture, and how to build it.

    `client` selects the transport shape; `camoufox_options` are merged into the
    browser launch; `headers` are extra request headers.

    `capabilities` is the *cumulative* set of axes in play at this rung, and
    `adds` is the single axis this rung introduces over the one below. The
    runner gates real work on these (acquiring a proxy only for a rung that
    rotates, planning a journey only for a rung that claims behavior), so the
    set has to match what the rung actually does, not just what it is called.
    """

    id: int
    key: str
    name: str
    description: str
    client: str  # "http" | "browser"
    camoufox_options: Dict[str, Any] = field(default_factory=dict)
    headers: Dict[str, str] = field(default_factory=dict)
    #: What this rung adds over the one below, in operator-facing terms.
    isolates: str = ""
    #: Cumulative capability axes active at this rung.
    capabilities: frozenset = frozenset()
    #: The one capability this rung introduces over the rung below.
    adds: Optional[str] = None

    @property
    def requires_rotation(self) -> bool:
        """True when this rung is *defined* by a fresh exit IP per visitor."""
        return "ip_rotation" in self.capabilities

    @property
    def is_behavioral(self) -> bool:
        """True when this rung is allowed to spend time behaving like a human."""
        return "behavior" in self.capabilities

    @property
    def is_persistent(self) -> bool:
        """True when this rung is defined by a durable profile."""
        return "persistence" in self.capabilities

    @property
    def navigation_headers(self) -> Dict[str, str]:
        """
        Headers the rung pins on its arrival navigation.

        Only the enforceable subset lives here. Firefox generates `Sec-Fetch-*`,
        `Upgrade-Insecure-Requests` and `Accept-Encoding` itself, and -- measured,
        not assumed -- a route cannot override or remove them, so declaring them
        would be a no-op that reads as a control. What remains is what the rung can
        actually set on the navigation it sends.
        """
        return dict(self.headers)

    @property
    def context_headers(self) -> Dict[str, str]:
        """
        Headers to set context-wide, for every request including subresources.

        Always empty. A navigation header stamped on a stylesheet is a synthetic
        tell -- `Accept: text/html` on a `.css` request is something no browser
        produces -- so the rung's headers are applied to the arrival navigation
        and nowhere else. Kept as a named property so a future rung cannot quietly
        reintroduce the mistake by writing `extra_http_headers` directly.
        """
        return {}

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "key": self.key,
            "name": self.name,
            "description": self.description,
            "client": self.client,
            "isolates": self.isolates,
            "adds": self.adds,
            "capabilities": sorted(self.capabilities),
            "requires_rotation": self.requires_rotation,
        }


#: A realistic modern Chrome UA on Windows. Kept for the header-consistency rung
#: and for any caller that audits a target which rejects Camoufox's own UA; the
#: ladder itself does not need it, because every browser rung lets Camoufox set a
#: UA that matches the fingerprint it generated. Sending a fixed Chrome UA from a
#: fingerprint that says "macOS" would be the exact inconsistency L2 exists to
#: rule out.
_CHROME_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)


EVASION_LEVELS: List[EvasionLevel] = [
    EvasionLevel(
        id=0,
        key="naive_http",
        name="L0 - Naive HTTP",
        description=(
            "Plain HTTP request with a default library User-Agent. No browser, "
            "no JavaScript, no cookies."
        ),
        client="http",
        capabilities=frozenset(),
        adds=None,
        isolates=(
            "The baseline everything else is measured against. If the defense "
            "cannot stop this, it is not protecting anything."
        ),
    ),
    EvasionLevel(
        id=1,
        key="headless_browser",
        name="L1 - Headless browser",
        description=(
            "Real Camoufox browser, headless, default fingerprint, no proxy, no "
            "humanization. Navigation headers are whatever the engine sends."
        ),
        client="browser",
        camoufox_options={"headless": True},
        capabilities=frozenset({"browser"}),
        adds="browser",
        isolates=(
            "Whether a stock headless browser is distinguishable at all. A "
            "defense that stops here is catching headless/automation tells, not "
            "fingerprint spoofing."
        ),
    ),
    EvasionLevel(
        id=2,
        key="header_consistency",
        name="L2 - Consistent headers",
        description=(
            "Headful browser with an explicit navigation header profile. On the "
            "arrival request the browser's own Sec-Fetch-Site: none already "
            "encodes a direct/typed arrival, so this rung pins the one header it "
            "can actually control -- the Accept the navigation is sent with, "
            "stated in Firefox's own form to match the engine and UA it is sent "
            "from -- and lets the engine generate the rest rather than "
            "overstating what it changed. Arrival Referer is a journey signal, so "
            "it belongs to the behavioral rung, not here."
        ),
        client="browser",
        camoufox_options={"headless": False},
        headers={
            # Only what the rung can actually change. Measured against the wire,
            # Firefox emits Sec-Fetch-Dest/Mode/Site/User and
            # Upgrade-Insecure-Requests itself and will not let them be
            # overridden or dropped, so declaring them here would be a no-op that
            # reads like a control. Accept is genuinely settable, and on the
            # arrival navigation the browser's own `Sec-Fetch-Site: none` already
            # says "typed URL", which is exactly the posture this rung means.
            #
            # The value is Firefox's own string, not Chromium's: Camoufox is a
            # Firefox engine sending a Firefox UA, and `image/avif,image/webp,
            # image/apng` in that position is Chromium's list. Pinning it would
            # manufacture the cross-engine inconsistency this audit exists to
            # detect -- an Accept that belongs to a browser the UA denies being.
            #
            # Cache-Control is absent for the same reason: `max-age=0` is
            # Chromium's reload header and Firefox sends none, so pinning it would
            # be another engine mismatch. Accept-Language is absent because
            # Camoufox derives it from the spoofed locale (see
            # patches/locale-spoofing.patch); pinning it would contradict
            # `navigator.language` on any non-en-US fingerprint.
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "*/*;q=0.8"
            ),
        },
        capabilities=frozenset({"browser", "headers"}),
        adds="headers",
        isolates=(
            "Header-level anomaly detection. Catches a defense that keys on "
            "missing or contradictory navigation headers rather than on the "
            "browser itself."
        ),
    ),
    EvasionLevel(
        id=3,
        key="fingerprint_mask",
        name="L3 - Fingerprint masking",
        description=(
            "Camoufox fingerprint spoofing enabled: spoofed OS, screen, hardware "
            "concurrency, WebGL, fonts, navigator properties, with geoip and "
            "timezone aligned."
        ),
        client="browser",
        camoufox_options={
            "headless": False,
            "geoip": True,
            "os": ["windows", "macos", "linux"],
        },
        headers={
            # The enforceable subset only; see the note on L2. Accept-Language
            # comes from the spoofed locale, not from here.
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "*/*;q=0.8"
            ),
        },
        capabilities=frozenset({"browser", "headers", "fingerprint"}),
        adds="fingerprint",
        isolates=(
            "Fingerprint-based filtering: canvas/WebGL hashes, navigator "
            "inconsistencies, screen metrics. This is the rung that tests the "
            "anti-detect engine itself."
        ),
    ),
    EvasionLevel(
        id=4,
        key="proxy_rotation",
        name="L4 - Proxy rotation",
        description=(
            "Fingerprint masking plus a fresh exit IP per visitor from the "
            "configured proxy pool, with the fingerprint's locale aligned to the "
            "proxy's geo."
        ),
        client="browser",
        camoufox_options={
            "headless": False,
            "geoip": True,
            "os": ["windows", "macos", "linux"],
        },
        headers={
            # The enforceable subset only; see the note on L2. Accept-Language
            # comes from the spoofed locale, not from here.
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "*/*;q=0.8"
            ),
        },
        capabilities=frozenset({"browser", "headers", "fingerprint", "ip_rotation"}),
        adds="ip_rotation",
        isolates=(
            "IP-reputation and rate-limit defenses. Tests whether the defense "
            "handles many distinct source IPs, i.e. whether it is only catching "
            "the easy single-IP case."
        ),
    ),
    EvasionLevel(
        id=5,
        key="behavioral",
        name="L5 - Human behavior",
        description=(
            "Proxy rotation plus a realistic visitor journey: plausible arrival "
            "source, dwell time, scrolling, mouse movement and typing at human "
            "cadence."
        ),
        client="browser",
        camoufox_options={
            "headless": False,
            "geoip": True,
            "os": ["windows", "macos", "linux"],
            "humanize": True,
        },
        headers={
            # The enforceable subset only; see the note on L2. Accept-Language
            # comes from the spoofed locale, not from here.
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "*/*;q=0.8"
            ),
        },
        capabilities=frozenset(
            {"browser", "headers", "fingerprint", "ip_rotation", "behavior"}
        ),
        adds="behavior",
        isolates=(
            "Behavioral / interaction analysis. Catches defenses that score "
            "mouse entropy, dwell time, or request cadence rather than the "
            "client's static properties."
        ),
    ),
    EvasionLevel(
        id=6,
        key="persistent_session",
        name="L6 - Persistent identity",
        description=(
            "Everything above, plus a persistent browser profile and cookies so "
            "the visitor returns as a recognized repeat visitor rather than a "
            "first-time client every time."
        ),
        client="browser",
        camoufox_options={
            "headless": False,
            "geoip": True,
            "os": ["windows", "macos", "linux"],
            "humanize": True,
            "persistent_context": True,
        },
        headers={
            # The enforceable subset only; see the note on L2. Accept-Language
            # comes from the spoofed locale, not from here.
            "Accept": (
                "text/html,application/xhtml+xml,application/xml;q=0.9,"
                "*/*;q=0.8"
            ),
        },
        capabilities=frozenset(
            {
                "browser",
                "headers",
                "fingerprint",
                "ip_rotation",
                "behavior",
                "persistence",
            }
        ),
        adds="persistence",
        isolates=(
            "Reputation / trust scoring over time. Tests whether the defense "
            "escalates on a client whose cookies and profile it has seen."
        ),
    ),
]

_BY_ID = {level.id: level for level in EVASION_LEVELS}


def ladder_problems(levels: Optional[List[EvasionLevel]] = None) -> List[str]:
    """
    Check the ladder's defining property: each rung adds exactly one capability.

    Returns a list of human-readable problems; empty means the ladder is sound.
    This is enforced as a test rather than trusted as a comment, because a rung
    that silently repeats the rung below it (or turns on two axes at once) makes
    a verdict unattributable -- which is the one thing the ladder exists to
    prevent.
    """
    levels = list(EVASION_LEVELS if levels is None else levels)
    problems: List[str] = []
    previous: frozenset = frozenset()
    for index, level in enumerate(levels):
        if level.id != index:
            problems.append(f"{level.name}: expected id {index}, got {level.id}")
        if level.capabilities < previous:
            problems.append(
                f"{level.name}: drops capability "
                f"{sorted(previous - level.capabilities)} that the rung below had"
            )
        added = level.capabilities - previous
        expected = set() if level.adds is None else {level.adds}
        if added != expected:
            problems.append(
                f"{level.name}: declares adds={level.adds!r} but actually changes "
                f"{sorted(added)}"
            )
        if level.adds is not None and level.adds not in CAPABILITIES:
            problems.append(f"{level.name}: unknown capability {level.adds!r}")
        if level.client == "browser" and "browser" not in level.capabilities:
            problems.append(f"{level.name}: a browser rung must declare 'browser'")
        if level.client == "http" and level.capabilities:
            problems.append(f"{level.name}: an HTTP rung must not claim capabilities")
        # A header the client cannot actually change makes the rung's `adds` claim
        # a no-op that still passes the capability check above, so it is caught
        # separately. See UNCONTROLLABLE_HEADERS.
        bogus = sorted(
            name
            for name in level.headers
            if name.lower() in UNCONTROLLABLE_HEADERS
        )
        if bogus:
            problems.append(
                f"{level.name}: declares header(s) {bogus} that the client cannot "
                f"actually control, so the rung changes nothing on the wire"
            )
        previous = level.capabilities
    return problems


def level_by_id(level_id: int) -> EvasionLevel:
    try:
        return _BY_ID[int(level_id)]
    except (KeyError, TypeError, ValueError):
        raise ValueError(
            f"Unknown evasion level {level_id!r}. Valid levels: "
            f"{sorted(_BY_ID)}"
        )


def levels_up_to(max_id: int) -> List[EvasionLevel]:
    """Levels 0..max_id inclusive, in order -- the usual way to run an audit."""
    return [level for level in EVASION_LEVELS if level.id <= int(max_id)]