# GENERATED by apps/audit-console/sync_engine.py -- do not edit.
#
# A copy of pythonlib/camoufox/audit/schedule.py, vendored so the console ships
# as one self-contained file. Edit the source and re-run the sync.
#
# Copied verbatim except for the browser imports noted below: the engine reaches
# for `..async_api` and `..proxy` lazily, from inside the browser rungs, and after
# relocation `..` no longer means `camoufox`. They are rewritten to the absolute
# package so an installed camoufox is used when present. Everything the HTTP rung
# needs (L0) stays dependency-free.

"""
Schedule N visitors across a window so they arrive like people, not like a job.

The requirement is "1000 visitors over 24 hours, not all at once and not evenly
spaced". That rules out both extremes and points at the actual shape of human
traffic: a non-homogeneous Poisson process. Arrivals are random, but the *rate*
varies over the day -- quiet at 04:00, busy in the evening -- which is what a
diurnal curve provides.

Uniform spacing is the giveaway. An evenly-spaced arrival stream has a variance
that real traffic never has, so it is trivially separable from humans by a
defense that looks at inter-arrival regularity. Poisson arrivals fix that while
still hitting the target count.

The scheduler also supports load-testing patterns (ramp, spike, sustained), which
are deliberate departures from the human curve and are used when the question is
capacity rather than detection.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from datetime import datetime, time, timedelta, timezone
from typing import List, Optional, Tuple

__all__ = [
    "ArrivalPattern",
    "ScheduleConfig",
    "Arrival",
    "build_schedule",
    "diurnal_rate",
]


class ArrivalPattern:
    """How arrivals are distributed across the window."""

    #: Clustered by time of day: quiet overnight, busy in the evening.
    HUMAN_DIURNAL = "human_diurnal"
    #: Even rate across the whole window.
    CONSTANT = "constant"
    #: Linearly increasing rate, for finding the breaking point.
    RAMP = "ramp"
    #: A quiet baseline with a sharp burst in the middle.
    SPIKE = "spike"
    #: A busy period then a quiet tail, for soak testing.
    SUSTAINED = "sustained"

    ALL = (HUMAN_DIURNAL, CONSTANT, RAMP, SPIKE, SUSTAINED)


def diurnal_rate(hour: float) -> float:
    """
    Relative traffic weight at a given hour of the day (0.0-24.0).

    Two peaks (a working-hours plateau and an evening high) with a deep overnight
    trough. This is the shape of consumer traffic to most sites. A single sine
    wave is smoother than reality but has the property that matters here: the
    rate is never constant, so arrivals cluster and thin out the way real ones do.
    """
    normalized = hour % 24.0
    # Peaks near 10:00 and 20:00, trough near 04:00.
    morning = math.exp(-((normalized - 10.0) ** 2) / (2 * 3.2**2))
    evening = math.exp(-((normalized - 20.0) ** 2) / (2 * 3.0**2))
    # A floor keeps the small hours non-zero, because a site is never truly dead.
    return 0.06 + 0.85 * max(morning, 0.75 * evening)


@dataclass
class ScheduleConfig:
    """Parameters for spreading visitors across a window."""

    visitor_count: int = 1000
    #: Window length. 24 hours by default, matching the "over a day" request.
    duration_hours: float = 24.0
    pattern: str = ArrivalPattern.HUMAN_DIURNAL
    #: Start of the window; defaults to "now" at schedule time.
    start_at: Optional[datetime] = None
    #: Local hour-of-day the window starts at, used to align the diurnal curve.
    #:
    #: None means "derive it from `start_at`" (falling back to the current local
    #: time when `start_at` is also None). Leaving it at a fixed 0.0 -- the original
    #: default -- anchored the curve to midnight regardless of when the run
    #: actually started, so a run begun at 14:00 local peaked at 24:00 and idled at
    #: 10:00. The daily pattern was inverted, which is worse than having no pattern:
    #: it is a specific, wrong signature.
    start_hour: Optional[float] = None
    #: Caps that keep a burst from becoming an accidental flood.
    max_arrivals_per_minute: int = 60
    #: Never schedule two arrivals closer than this, in seconds.
    min_gap_s: float = 1.0
    #: Random jitter applied to each arrival, in seconds.
    jitter_s: float = 45.0
    #: Assumed visitor session length, used only for reporting overlap.
    session_seconds: float = 120.0

    def __post_init__(self) -> None:
        if self.visitor_count < 0:
            raise ValueError("visitor_count cannot be negative")
        if self.duration_hours <= 0:
            raise ValueError("duration_hours must be positive")
        if self.pattern not in ArrivalPattern.ALL:
            raise ValueError(
                f"Unknown pattern {self.pattern!r}; expected one of {ArrivalPattern.ALL}"
            )

    def resolved_start_hour(self) -> float:
        """
        The hour-of-day the diurnal curve should be anchored to.

        Derived from the window's start so the curve covers the hours the run
        actually occupies. Callers that mean a specific hour can still pin
        `start_hour`, which wins.
        """
        if self.start_hour is not None:
            return float(self.start_hour) % 24.0
        start = self.start_at or datetime.now().astimezone()
        return (start.hour + start.minute / 60.0 + start.second / 3600.0) % 24.0


@dataclass
class Arrival:
    """One scheduled visitor arrival."""

    index: int
    at: datetime
    offset_s: float

    def to_dict(self) -> dict:
        return {
            "index": self.index,
            "at": self.at.isoformat(),
            "offset_s": round(self.offset_s, 3),
        }


@dataclass
class Schedule:
    """A built arrival schedule."""

    arrivals: List[Arrival] = field(default_factory=list)
    config: Optional[ScheduleConfig] = None
    warnings: List[str] = field(default_factory=list)

    @property
    def count(self) -> int:
        return len(self.arrivals)

    def inter_arrival_seconds(self) -> List[float]:
        return [
            (b.at - a.at).total_seconds()
            for a, b in zip(self.arrivals, self.arrivals[1:])
        ]

    def describe(self) -> str:
        if not self.arrivals:
            return "empty schedule"
        span = (self.arrivals[-1].at - self.arrivals[0].at).total_seconds()
        gaps = self.inter_arrival_seconds()
        mean_gap = sum(gaps) / len(gaps) if gaps else 0.0
        var = (
            sum((g - mean_gap) ** 2 for g in gaps) / len(gaps) if gaps else 0.0
        )
        return (
            f"{self.count} visitors over {span / 3600:.2f}h "
            f"(mean gap {mean_gap:.0f}s, stdev {math.sqrt(var):.0f}s, "
            f"pattern {self.config.pattern if self.config else '?'})"
        )

    def to_dict(self) -> dict:
        return {
            "count": self.count,
            "config": {
                "visitor_count": self.config.visitor_count,
                "duration_hours": self.config.duration_hours,
                "pattern": self.config.pattern,
            } if self.config else None,
            "warnings": list(self.warnings),
            "arrivals": [a.to_dict() for a in self.arrivals],
        }


# ---------------------------------------------------------------------------
# Pattern rate functions
# ---------------------------------------------------------------------------
#
# Each returns a *relative* arrival intensity for a normalized position in the
# window (0.0 = start, 1.0 = end). build_schedule integrates these.

def _rate_human_diurnal(t: float, cfg: ScheduleConfig) -> float:
    hour = (cfg.resolved_start_hour() + t * cfg.duration_hours) % 24.0
    return diurnal_rate(hour)


def _rate_constant(t: float, cfg: ScheduleConfig) -> float:
    return 1.0


def _rate_ramp(t: float, cfg: ScheduleConfig) -> float:
    # Non-zero at the start so the run begins immediately but gently.
    return 0.05 + t


def _rate_spike(t: float, cfg: ScheduleConfig) -> float:
    return 0.08 + 1.4 * math.exp(-((t - 0.5) ** 2) / (2 * 0.06**2))


def _rate_sustained(t: float, cfg: ScheduleConfig) -> float:
    if t < 0.5:
        return 1.0
    # Decay to a quiet tail over the second half.
    return max(0.08, 1.0 - (t - 0.5) * 1.8)


_RATE_FUNCTIONS = {
    ArrivalPattern.HUMAN_DIURNAL: _rate_human_diurnal,
    ArrivalPattern.CONSTANT: _rate_constant,
    ArrivalPattern.RAMP: _rate_ramp,
    ArrivalPattern.SPIKE: _rate_spike,
    ArrivalPattern.SUSTAINED: _rate_sustained,
}


def build_schedule(config: ScheduleConfig, rng: Optional[random.Random] = None) -> Schedule:
    """
    Build the arrival schedule.

    Inverse-transform sampling on the pattern's cumulative intensity: we want
    arrivals distributed according to the rate curve, and this does that without
    rejection sampling, so the count is exact and the runtime is linear.
    """
    rng = rng or random.Random()
    warnings: List[str] = []

    if config.visitor_count == 0:
        return Schedule(arrivals=[], config=config, warnings=["No visitors requested."])

    rate_fn = _RATE_FUNCTIONS[config.pattern]
    window_s = config.duration_hours * 3600.0
    if config.start_at is not None:
        start = config.start_at
    else:
        # Anchor the window to the same clock the diurnal curve is aligned to, so
        # the two cannot disagree about which hour the run starts at.
        start = datetime.now().astimezone()

    # Dense sampling of the intensity curve, then its cumulative integral.
    steps = 2000
    xs = [i / (steps - 1) for i in range(steps)]
    ys = [rate_fn(x, config) for x in xs]
    cumulative = [0.0]
    for i in range(1, steps):
        # Trapezoid on a uniform grid.
        dx = xs[i] - xs[i - 1]
        cumulative.append(cumulative[-1] + 0.5 * (ys[i] + ys[i - 1]) * dx)
    total = cumulative[-1]
    if total <= 0:
        warnings.append("Pattern produced no intensity; falling back to uniform.")
        cumulative = xs[:]
        total = 1.0

    def invert(u: float) -> float:
        """Find t such that cumulative(t)/total == u."""
        target = u * total
        lo, hi = 0, steps - 1
        while lo < hi:
            mid = (lo + hi) // 2
            if cumulative[mid] < target:
                lo = mid + 1
            else:
                hi = mid
        if lo == 0:
            return 0.0
        prev_c, cur_c = cumulative[lo - 1], cumulative[lo]
        span = cur_c - prev_c
        frac = 0.0 if span <= 0 else (target - prev_c) / span
        return xs[lo - 1] + frac * (xs[lo] - xs[lo - 1])

    offsets = sorted(invert(rng.random()) for _ in range(config.visitor_count))

    # Jitter, then a global min-gap pass so jitter cannot create an implausible
    # pile-up. Both matter: without jitter the quantiles are too regular, and
    # without the gap pass a lucky cluster looks like a burst.
    jittered = [
        min(max(o * window_s + rng.uniform(-config.jitter_s, config.jitter_s), 0.0), window_s)
        for o in offsets
    ]
    jittered.sort()

    enforced: List[float] = []
    for offset in jittered:
        if enforced and offset - enforced[-1] < config.min_gap_s:
            offset = enforced[-1] + config.min_gap_s
        enforced.append(offset)

    if enforced and enforced[-1] > window_s:
        warnings.append(
            f"Min-gap floor pushed the last arrival past the {config.duration_hours:g}h "
            f"window. Widen the window, lower the visitor count, or reduce min_gap_s."
        )

    # Rate ceiling: if the busiest minute exceeds the cap, report it rather than
    # silently reshaping the run, because it changes what the audit actually tests.
    per_minute = _max_per_minute(enforced)
    if per_minute > config.max_arrivals_per_minute:
        warnings.append(
            f"Peak arrival rate is {per_minute}/min, above the configured ceiling of "
            f"{config.max_arrivals_per_minute}/min. The audit will honor the ceiling, "
            f"which may stretch the schedule past the window."
        )
        enforced = _enforce_per_minute_ceiling(enforced, config.max_arrivals_per_minute)

    arrivals = [
        Arrival(index=i, at=start + timedelta(seconds=offset), offset_s=offset)
        for i, offset in enumerate(enforced)
    ]
    return Schedule(arrivals=arrivals, config=config, warnings=warnings)


def _max_per_minute(offsets: List[float]) -> int:
    """Largest number of arrivals falling inside any 60-second window."""
    if not offsets:
        return 0
    best = 0
    j = 0
    for i in range(len(offsets)):
        while offsets[i] - offsets[j] > 60.0:
            j += 1
        best = max(best, i - j + 1)
    return best


def _enforce_per_minute_ceiling(offsets: List[float], ceiling: int) -> List[float]:
    """Push arrivals later until no minute holds more than `ceiling` of them."""
    if ceiling <= 0:
        return offsets
    out: List[float] = []
    window: List[float] = []
    for offset in offsets:
        window = [o for o in window if offset - o < 60.0]
        if len(window) >= ceiling:
            # Slide forward just past the oldest arrival in the full minute.
            offset = window[0] + 60.0001
            window = [o for o in window if offset - o < 60.0]
        out.append(offset)
        window.append(offset)
    return out