# GENERATED by apps/audit-console/sync_engine.py -- do not edit.
#
# A copy of pythonlib/camoufox/audit/scope.py, vendored so the console ships
# as one self-contained file. Edit the source and re-run the sync.
#
# Copied verbatim except for the browser imports noted below: the engine reaches
# for `..async_api` and `..proxy` lazily, from inside the browser rungs, and after
# relocation `..` no longer means `camoufox`. They are rewritten to the absolute
# package so an installed camoufox is used when present. Everything the HTTP rung
# needs (L0) stays dependency-free.

"""
Scope enforcement for the WAF / bot-defense audit tool.

The audit tool drives Camoufox at a target the operator does not control from
inside this process. Everything in this package is therefore gated behind an
explicit, narrow, verifiable scope: a target must be named *and* acknowledged as
authorized before any request is allowed to leave.

The gate is enforced here, at the single point every scheduled request passes
through, rather than trusted to the caller. A UI checkbox is a reminder, not a
security control; this is the control.
"""

from __future__ import annotations

import ipaddress
from dataclasses import dataclass, field
from typing import List, Sequence, Set
from urllib.parse import urlparse

__all__ = [
    "ScopeViolation",
    "AuthorizationRequired",
    "TargetScope",
]


class ScopeViolation(RuntimeError):
    """A request was aimed outside the authorized target scope."""


class AuthorizationRequired(RuntimeError):
    """The audit was started without an authorization acknowledgment."""


def _normalize_host(host: str) -> str:
    host = (host or "").strip().lower().rstrip(".")
    if host.startswith("[") and host.endswith("]"):
        host = host[1:-1]
    return host


def _is_ip_literal(host: str) -> bool:
    try:
        ipaddress.ip_address(host)
        return True
    except ValueError:
        return False


@dataclass
class TargetScope:
    """
    The set of hosts an audit is permitted to touch.

    Matching is exact-host plus explicitly listed subdomains; a bare domain does
    *not* implicitly authorize every subdomain, because a wildcard scope is how
    an audit accidentally reaches a third-party property that shares a suffix.
    """

    hosts: List[str] = field(default_factory=list)
    allow_subdomains: bool = False
    acknowledged: bool = False
    acknowledgment_note: str = ""
    #: Operator-declared campaign/partner destinations for the outbound funnel.
    #:
    #: Named up front, exactly like the audited hosts, because the alternative --
    #: authorizing whatever host a banner happens to link to -- hands the target
    #: control over what this tool may touch. Discovery is dynamic; authorization
    #: is not.
    outbound_hosts: List[str] = field(default_factory=list)
    #: Hosts actually admitted from `outbound_hosts` during this session.
    #:
    #: Populated by `authorize_outbound()` so a report can state precisely which
    #: destinations the run touched, rather than only which were declared.
    session_outbound: Set[str] = field(default_factory=set)

    def __post_init__(self) -> None:
        self.hosts = [_normalize_host(h) for h in self.hosts if _normalize_host(h)]
        self.outbound_hosts = [
            _normalize_host(h) for h in self.outbound_hosts if _normalize_host(h)
        ]

    # -- construction ------------------------------------------------------

    @classmethod
    def from_urls(
        cls,
        urls: Sequence[str],
        *,
        allow_subdomains: bool = False,
        acknowledged: bool = False,
        acknowledgment_note: str = "",
        outbound_urls: Sequence[str] = (),
    ) -> "TargetScope":
        hosts: List[str] = []
        for url in urls:
            parsed = urlparse(url if "//" in url else f"//{url}")
            host = parsed.hostname
            if not host:
                raise ValueError(f"Could not parse a host out of {url!r}")
            hosts.append(host)
        outbound_hosts: List[str] = []
        for url in outbound_urls:
            parsed = urlparse(url if "//" in url else f"//{url}")
            host = parsed.hostname
            if not host:
                raise ValueError(f"Could not parse a host out of {url!r}")
            outbound_hosts.append(host)
        return cls(
            hosts=hosts,
            allow_subdomains=allow_subdomains,
            acknowledged=acknowledged,
            acknowledgment_note=acknowledgment_note,
            outbound_hosts=outbound_hosts,
        )

    # -- the gate ----------------------------------------------------------

    def check(self, url: str) -> str:
        """
        Return the normalized host for `url`, or raise.

        Every navigation goes through here, so there is exactly one place that
        decides whether a request is in scope.
        """
        if not self.acknowledged:
            raise AuthorizationRequired(
                "Refusing to send traffic: the audit has not been acknowledged as "
                "authorized. The operator must confirm they own the target or have "
                "written permission to test it."
            )
        if not self.hosts:
            raise ScopeViolation(
                "Refusing to send traffic: the target scope is empty. Name the "
                "hosts under test before starting the audit."
            )

        parsed = urlparse(url)
        scheme = (parsed.scheme or "").lower()
        if scheme not in ("http", "https"):
            raise ScopeViolation(
                f"Refusing to fetch {url!r}: only http/https targets are audited."
            )

        host = _normalize_host(parsed.hostname or "")
        if not host:
            raise ScopeViolation(f"Refusing to fetch {url!r}: no host in URL.")
        if not self.permits(host):
            raise ScopeViolation(
                f"Refusing to fetch {host!r}: outside the authorized scope "
                f"({', '.join(self.hosts)}). The audit will not touch hosts that "
                f"were not named."
            )
        return host

    def permits(self, host: str) -> bool:
        """Host-only check, for pre-flight validation without raising."""
        host = _normalize_host(host)
        if not host:
            return False
        for allowed in self.hosts:
            if host == allowed:
                return True
            if self.allow_subdomains and not _is_ip_literal(allowed):
                if host.endswith("." + allowed):
                    return True
        return False

    def permits_url(self, url: str) -> bool:
        host = _normalize_host(urlparse(url).hostname or "")
        return self.permits(host)

    # -- session-scoped outbound authorization -----------------------------
    #
    # The outbound-funnel audit follows promotional banners to the destination
    # they point at, and that destination is often a partner or campaign host
    # outside the site being audited. The convenience everyone reaches for --
    # "the page linked it, so let the page widen the scope" -- would let the
    # target choose what this tool is authorized to touch, which is the one
    # thing the gate exists to prevent (a link can be injected, and an audit
    # that follows any of them is an open request forwarder).
    #
    # So the ordering is explicit and stays operator-driven: the operator names
    # the destinations up front (`outbound_hosts`), and `authorize_outbound()`
    # admits exactly those, one hop at a time, for the duration of the run.
    # Discovery is still dynamic -- it is read from the DOM at visit time -- but
    # a discovered host that the operator never named is refused and *recorded*,
    # not followed. `check_unattended()` is the non-raising form the discovery
    # path uses so a third-party banner is reported rather than fatal.

    def authorize_outbound(self, url: str) -> bool:
        """
        Admit one operator-declared outbound destination for this session.

        Returns False without raising when the host was not declared, so the
        discovery path can record it. Returns True when it is now authorized
        (already in scope, or named in `outbound_hosts`).

        Refuses, deliberately: any non-http(s) scheme, an IP-literal host (the
        cloud metadata endpoint is a literal, and so is any internal service a
        campaign link could be tricked into naming), and a host that merely
        ends with a declared partner's name (`evil-partner.com`).
        """
        parsed = urlparse(url)
        if (parsed.scheme or "").lower() not in ("http", "https"):
            return False
        host = _normalize_host(parsed.hostname or "")
        if not host or _is_ip_literal(host):
            return False
        if self.permits(host):
            return True
        if host in self._outbound_allowed():
            self.session_outbound.add(host)
            return True
        return False

    def _outbound_allowed(self) -> Set[str]:
        allowed: Set[str] = set()
        for entry in self.outbound_hosts:
            allowed.add(_normalize_host(entry))
        return allowed

    def check_unattended(self, url: str) -> bool:
        """
        The discovery path's check: does the outbound gate permit this URL?

        Deliberately shaped like `check()` minus the raise. The funnel walk uses
        this so an unauthorized third-party banner is a recorded finding rather
        than an exception that aborts the visit -- the audit should report the
        off-scope destination, not die on it. It still authorizes through
        `authorize_outbound()`, so nothing reaches a socket that the gate refused.
        """
        if not self.acknowledged or not self.hosts:
            return False
        return self.authorize_outbound(url)

    def outbound_description(self) -> str:
        declared = ", ".join(sorted(self.outbound_hosts)) or "(none)"
        admitted = ", ".join(sorted(self.session_outbound)) or "(none)"
        return f"declared: {declared}; admitted this session: {admitted}"

    # -- description -------------------------------------------------------

    def describe(self) -> str:
        scope = ", ".join(self.hosts) if self.hosts else "(none)"
        suffix = " + subdomains" if self.allow_subdomains else ""
        return f"{scope}{suffix}"

    def to_dict(self) -> dict:
        return {
            "hosts": list(self.hosts),
            "allow_subdomains": self.allow_subdomains,
            "acknowledged": self.acknowledged,
            "acknowledgment_note": self.acknowledgment_note,
            "outbound_hosts": list(self.outbound_hosts),
            "session_outbound": sorted(self.session_outbound),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "TargetScope":
        return cls(
            hosts=list(data.get("hosts") or []),
            allow_subdomains=bool(data.get("allow_subdomains")),
            acknowledged=bool(data.get("acknowledged")),
            acknowledgment_note=str(data.get("acknowledgment_note") or ""),
            outbound_hosts=list(data.get("outbound_hosts") or []),
            session_outbound=set(data.get("session_outbound") or ()),
        )